"""baseline schema

Revision ID: a199fe9234b2
Revises: 
Create Date: 2026-07-10 01:11:35.579550+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a199fe9234b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('parent_account_id', sa.String(length=36), nullable=True),
    sa.Column('meta_page_id', sa.String(length=100), nullable=True),
    sa.Column('meta_page_name', sa.String(length=255), nullable=True),
    sa.Column('meta_access_token', sa.Text(), nullable=True),
    sa.Column('meta_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meta_page_id')
    )
    op.create_index(op.f('ix_accounts_parent_account_id'), 'accounts', ['parent_account_id'], unique=False)
    op.create_table('meta_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('meta_user_id', sa.String(length=100), nullable=True),
    sa.Column('page_id', sa.String(length=100), nullable=True),
    sa.Column('ig_business_account_id', sa.String(length=100), nullable=True),
    sa.Column('waba_id', sa.String(length=100), nullable=True),
    sa.Column('ad_account_id', sa.String(length=100), nullable=True),
    sa.Column('phone_number_id', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('meta_templates', sa.JSON(), nullable=True),
    sa.Column('conv_count_marketing', sa.Integer(), nullable=False),
    sa.Column('conv_count_utility', sa.Integer(), nullable=False),
    sa.Column('conv_count_service', sa.Integer(), nullable=False),
    sa.Column('conv_count_auth', sa.Integer(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meta_conn_account_provider', 'meta_connections', ['account_id', 'provider'], unique=False)
    op.create_index('ix_meta_conn_ig_biz', 'meta_connections', ['ig_business_account_id'], unique=False)
    op.create_index('ix_meta_conn_page_id', 'meta_connections', ['page_id'], unique=False)
    op.create_index('ix_meta_conn_phone_number_id', 'meta_connections', ['phone_number_id'], unique=False)
    op.create_index('ix_meta_conn_waba', 'meta_connections', ['waba_id'], unique=False)
    op.create_index(op.f('ix_meta_connections_account_id'), 'meta_connections', ['account_id'], unique=False)
    op.create_table('post_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('ig_user_id', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('automation_keyword', sa.String(length=255), nullable=True),
    sa.Column('automation_comment_reply', sa.Text(), nullable=True),
    sa.Column('automation_dm_message', sa.Text(), nullable=True),
    sa.Column('automation_link_message', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('media_id_response', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_schedules_account_id'), 'post_schedules', ['account_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_account_id'), 'alerts', ['account_id'], unique=False)
    op.create_table('automation_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('auto_reply_message', sa.Text(), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('media_id', sa.String(length=100), nullable=True),
    sa.Column('comment_reply_message', sa.Text(), nullable=True),
    sa.Column('dm_message', sa.Text(), nullable=True),
    sa.Column('link_message', sa.Text(), nullable=True),
    sa.Column('handoff_to_human', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_configs_account_id'), 'automation_configs', ['account_id'], unique=False)
    op.create_index(op.f('ix_automation_configs_media_id'), 'automation_configs', ['media_id'], unique=False)
    op.create_table('credit_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('total_credits', sa.Integer(), nullable=False),
    sa.Column('used_credits', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_usage_account_id'), 'credit_usage', ['account_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('instagram_handle', sa.String(length=100), nullable=False),
    sa.Column('ig_user_id', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('alt_handles', sa.Text(), nullable=True),
    sa.Column('pending_auto_message', sa.Text(), nullable=True),
    sa.Column('pending_handoff', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('INSTAGRAM_COMMENT', 'INSTAGRAM_DM', 'INSTAGRAM_FORM', 'MANUAL', name='lead_source', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'CONVERTED', 'LOST', name='lead_status', create_constraint=True), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('score_label', sa.String(length=20), nullable=True),
    sa.Column('score_notes', sa.Text(), nullable=True),
    sa.Column('last_scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_account_id'), 'leads', ['account_id'], unique=False)
    op.create_index(op.f('ix_leads_instagram_handle'), 'leads', ['instagram_handle'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('asaas_payment_id', sa.String(length=100), nullable=True),
    sa.Column('asaas_customer_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_account_id'), 'subscriptions', ['account_id'], unique=False)
    op.create_index('ix_subscriptions_account_plan', 'subscriptions', ['account_id', 'plan'], unique=False)
    op.create_index('ix_subscriptions_asaas_payment_id', 'subscriptions', ['asaas_payment_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_username', 'users', ['tenant_id', 'username'], unique=False)
    op.create_table('video_generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_generations_account_id'), 'video_generations', ['account_id'], unique=False)
    op.create_table('client_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('client_account_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_account_id', name='uq_assignment_user_client')
    )
    op.create_index('ix_assignment_user_client', 'client_assignments', ['user_id', 'client_account_id'], unique=False)
    op.create_index(op.f('ix_client_assignments_client_account_id'), 'client_assignments', ['client_account_id'], unique=False)
    op.create_index(op.f('ix_client_assignments_user_id'), 'client_assignments', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('atendente_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('atendimento_status', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('bot_active', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['atendente_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conv_tenant_atendente', 'conversations', ['tenant_id', 'atendente_id'], unique=False)
    op.create_index('ix_conv_tenant_channel', 'conversations', ['tenant_id', 'channel'], unique=False)
    op.create_index('ix_conv_tenant_status', 'conversations', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_conversations_atendente_id'), 'conversations', ['atendente_id'], unique=False)
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_account_id'), 'customers', ['account_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('wa_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('media_type', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=2048), nullable=True),
    sa.Column('context_text', sa.Text(), nullable=True),
    sa.Column('meta_category', sa.String(length=50), nullable=True),
    sa.Column('meta_cost', sa.Float(), nullable=True),
    sa.Column('is_within_24h_window', sa.Boolean(), nullable=False),
    sa.Column('template_vars', sa.JSON(), nullable=True),
    sa.Column('template_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_index('ix_msg_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_account_id'), 'sales', ['account_id'], unique=False)
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_account_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_msg_conversation_created', table_name='messages')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_customers_account_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_atendente_id'), table_name='conversations')
    op.drop_index('ix_conv_tenant_status', table_name='conversations')
    op.drop_index('ix_conv_tenant_channel', table_name='conversations')
    op.drop_index('ix_conv_tenant_atendente', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_client_assignments_user_id'), table_name='client_assignments')
    op.drop_index(op.f('ix_client_assignments_client_account_id'), table_name='client_assignments')
    op.drop_index('ix_assignment_user_client', table_name='client_assignments')
    op.drop_table('client_assignments')
    op.drop_index(op.f('ix_video_generations_account_id'), table_name='video_generations')
    op.drop_table('video_generations')
    op.drop_index('ix_users_tenant_username', table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_subscriptions_asaas_payment_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_account_plan', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_account_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_leads_instagram_handle'), table_name='leads')
    op.drop_index(op.f('ix_leads_account_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_credit_usage_account_id'), table_name='credit_usage')
    op.drop_table('credit_usage')
    op.drop_index(op.f('ix_automation_configs_media_id'), table_name='automation_configs')
    op.drop_index(op.f('ix_automation_configs_account_id'), table_name='automation_configs')
    op.drop_table('automation_configs')
    op.drop_index(op.f('ix_alerts_account_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_post_schedules_account_id'), table_name='post_schedules')
    op.drop_table('post_schedules')
    op.drop_index(op.f('ix_meta_connections_account_id'), table_name='meta_connections')
    op.drop_index('ix_meta_conn_waba', table_name='meta_connections')
    op.drop_index('ix_meta_conn_phone_number_id', table_name='meta_connections')
    op.drop_index('ix_meta_conn_page_id', table_name='meta_connections')
    op.drop_index('ix_meta_conn_ig_biz', table_name='meta_connections')
    op.drop_index('ix_meta_conn_account_provider', table_name='meta_connections')
    op.drop_table('meta_connections')
    op.drop_index(op.f('ix_accounts_parent_account_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
